// Project Action Types
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const DELETE_PROJECTS_ERROR = 'DELETE_PROJECTS_ERROR'

// Task Action Types
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';
export const CHANGE_TASK_STATUS_SUCCESS = 'CHANGE_TASK_STATUS_SUCCESS';
export const CHANGE_TASK_STATUS_ERROR = 'CHANGE_TASK_STATUS_ERROR';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';
