export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const DELETE_PROJECTS_ERROR = 'DELETE_PROJECTS_ERROR'